#### CARICAMENTO  DATI####

#### CREARE TIBBLE ####

#### HIST CON DATI QUESTIONARIO ####

#### CALCOLO MISURE PER LIBRO ####
# ADEGUATEZZA MEDIA
# MAX
# MIN

#### AGGREGAZIONE TRA LIBRI ####
# ADEGUATEZZA MEDIA
# MSE 
# LIBRO CON ADEGUATEZZA MAX

#### GIUSTIFICAZIONI ####
# LUNGHEZZA MEDIA
# MAX
# MIN

#### DESCRIZIONE RISULTATI ####
# 2 DIM A PIACERE
# RISULTATI COMBO APPREZZAMENTO E POSSESSO DEL LIBRO
# RISULTATI COMBO APPREZZAMENTO E LETTURA DELL'AUTORE

###############################################################################

#### EXTRA ####
# AGGREGARE RISU QUEST CON DATI SUI LIBRI
# ANALISI DELLE RISPOSTE CON CODICE FRANCESCHET (SENTIMENT ANALYSIS)
# ANALISI TEMPI PER RISPOSTA
# CRT
